### ISSUE TITLE
[Bug]: In a multi panel app it doesn't create resources inside the panel namespace.

### ISSUE THREAD

**Issue by rezwanul7** [savannabits/filament-modules#109] opened 2024-07-15 11:28 UTC
### What happened?

In a multipanel app when running `php artisan module:make:filament-resource` asks about the panel. But it doesn't generate the resources inside the folder belonging to the panel.

### How to reproduce the bug

Create a multipanel app i.e. org, team. Run `php artisan module:make:filament-resource`. It will ask about the panel and select org.

### Package Version

4.0.6

### PHP Version

8.2.0

### Laravel Version

11.15.0

### Which operating systems does with happen with?

Windows

**Comment by coolsam726** [comment] 2024-07-16 05:49
Hi @rezwanul7,
I have tried to reproduce your issue above but I couldn't. I have created a bare minimum setup by following the package's documentation and it works perfectly. I followed these steps:
1. Created a new Laravel Project
2. Ran composer to install coolsam/modules, which by default installs all the other dependencies including filament and nwidart/laravel-modules.
3. Configured Filament (filament:install) and created two Panels: **Org** and **Team**
4. Opened the **Org** Panel and added the **ModulesPlugin** there (My highest suspicion is that you may have skipped this). Here is how my Org panel looks like:
![image](https://github.com/user-attachments/assets/175dfb7f-2655-4ff6-b1d6-e83fcab5592e)

5. Configured nwidart/modules as per the documentation, including adding the folllowing to composer.json:
![image](https://github.com/user-attachments/assets/c989861f-6095-45d2-a5ff-47834e7c2a59)

6. Created a new Module called Procurement: `php artisan module:make Procurement`
7. Added a new model called Supplier to the Procurement module with a factory, seeder and migration: `php artisan module:make-model Supplier -mfs Procurement`
![image](https://github.com/user-attachments/assets/359e4cce-e044-4959-8f78-cf3df55a3066)

8. Installed the **Filament Modules Plugin** under the Procurement Module: `php artisan module:filament:install`. Here are my steps:
![image](https://github.com/user-attachments/assets/3b28ad40-a198-4110-b814-2c52bb11dcb6)

9. Finally generated a **Suppliers Resource** under the Procurement module, after running php artisan migrate. Here are my steps:
![image](https://github.com/user-attachments/assets/e061b630-6fcb-41be-a1ba-1ce8258e60dd)

After going through the above steps, here is my working app:
![image](https://github.com/user-attachments/assets/e21e3e7a-3587-4eaa-8883-5c603d80044c)

Feel free share your reproduction repo in case you are still experiencing challenges. Closing this for now.

**Closed by coolsam726** 2024-07-16 05:49 UTC
Labels: question

**Comment by coolsam726** [comment] 2024-07-16 05:54
> ### What happened?
> In a multipanel app when running `php artisan module:make:filament-resource` asks about the panel. But it doesn't generate the resources inside the folder belonging to the panel.
> 
> ### How to reproduce the bug
> Create a multipanel app i.e. org, team. Run `php artisan module:make:filament-resource`. It will ask about the panel and select org.
> 
> ### Package Version
> 4.0.6
> 
> ### PHP Version
> 8.2.0
> 
> ### Laravel Version
> 11.15.0
> 
> ### Which operating systems does with happen with?
> Windows
> 
> ### Notes
> _No response_

Just to clarify, the whole idea of using this package is to gain autonomy from the main app/ directory, so resources are not generated in the panel folder, they are rather generated inside the **Module** of your choice. Here is a sample directory structure for a Procurement module registered under the Org panel:
![image](https://github.com/user-attachments/assets/d45f89d7-d77e-4f05-aeea-e05024b27805)
