### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mike-Hawwke** [savannabits/filament-modules#92] opened 2024-04-19 11:39 UTC
### What happened?

Hello,

I have installed your plugin in my Filament v3 (Laravel 11) installation.
When I do -> php artisan module:make:filament-resource (Document) and I generate the resource, I get an error that appears:

Class "Modules/Document/Providers/DocumentServiceProvider" not found

If I move the provider folder to the root of the plugin folder, it works.

But the new resource does not appear in the Filament menus after generating the model and migration.

thx

### How to reproduce the bug

Basic installation with latest version of laravel and module
follow the installation steps

### Package Version

v4.x

### PHP Version

8.2

### Laravel Version

11

**Comment by coolsam726** [comment] 2024-04-19 11:49
That's strange, kindly show me the exact command that you ran and you modules structure.
Also, let me know if you published the module's configs or not, for ease of reproduction.

**Comment by coolsam726** [comment] 2024-04-19 12:27
I see. Just curious, did you go through the following process?
![image](https://github.com/savannabits/filament-modules/assets/5610289/9a25fd43-5a4c-4632-8918-f14a693a6903)
This module depends on nwidart/laravel-modules being configured and working properly. If you didn't go through its documentation, you might have missed a step which ensures modules are auto-discovered by the parent app.
I am specifically suspecting this part of the documetation:
![image](https://github.com/savannabits/filament-modules/assets/5610289/8d31fed1-3584-41ea-b383-2d3b2f98d1a5)

**Comment by Mike-Hawwke** [comment] 2024-04-19 12:43
the extra is in the composer.json (see screen)

Even if in the doc it is indicated that since version 11 this was no longer necessary I added it just in case
![2024-04-19 144156](https://github.com/savannabits/filament-modules/assets/166394362/cff5d037-4126-4621-a1c5-846cc9733daf)

**Comment by coolsam726** [comment] 2024-04-19 13:23
I am afraid I cannot reproduce the error, I even created an app from scratch just to try and reproduce, but it is working fine.
![image](https://github.com/savannabits/filament-modules/assets/5610289/925827e6-fd75-44d3-8e9c-6dbb32206a6b)
However, I noticed from your screenshot that you are using windows. I don't have a windows machine and I always develop on Linux, so it is possible that this bug occurs on Windows. Can someone else confirm this?

**Comment by Mike-Hawwke** [comment] 2024-04-19 13:37
Can you give me access to this project to see the differences between yours and mine?

**Comment by coolsam726** [comment] 2024-04-19 14:03
I didn't push it to a repo yet. However, I wrote a test to check the `convertPathToNamespace` method which seems to be the cause of your failure, and the test is passing on linux but failing on windows, so I can almost certainly confirm that this is a bug with the function on the windows platform. Let me attempt a fix and update you.

**Comment by Mike-Hawwke** [comment] 2024-04-19 15:45
Thank you for your intervention

After udpate of the module I carried out the commands

php artisan module:make Document
I first had an error at the same step but it was different and referred to a problem with Nwidart

I did some research and came across this
https://github.com/nWidart/laravel-modules/issues/4

So I applied the modification to config/models.php in the generator

The error disappeared so I performed the second command

php artisan module:filament:install Document

A second error has occurred
https://flareapp.io/share/x7XaAzY5



I will share my progress with you if I find the reason

**Comment by Mike-Hawwke** [comment] 2024-04-19 16:06
When trying to create the resource I got this error (see screen)
![2024-04-19 180329](https://github.com/savannabits/filament-modules/assets/166394362/003fc41f-119c-4fd4-9c76-def9bfa98721)


I wonder while searching there I came across
getModulePlugins

This one also contains a path, possible that the problem is linked to Windows as above?

**Comment by coolsam726** [comment] 2024-04-19 19:03
> When trying to create the resource I got this error (see screen) ![2024-04-19 180329](https://private-user-images.githubusercontent.com/166394362/324030711-003fc41f-119c-4fd4-9c76-def9bfa98721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NTM1MTIsIm5iZiI6MTcxMzU1MzIxMiwicGF0aCI6Ii8xNjYzOTQzNjIvMzI0MDMwNzExLTAwM2ZjNDFmLTExOWMtNGZkNC05Yzc2LWRlZjliZmE5ODcyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxOTAwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzljMjcxM2RhNWNmMDE3ZDcwOWJjODZkYzA5MzgwMmVkYjY2YjNhYjJhMjMyMTJhYWI5NmY0NTU0YjgyMmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xjESb4jJekIgxaCBDJgDTzU9njUWsOqdTyip0nLp9V4)
> 
> I wonder while searching there I came across getModulePlugins
> 
> This one also contains a path, possible that the problem is linked to Windows as above?

It is definitely a bug only with windows, my methods are mixing up DIRECTORY SEPARATORS. I think I will have to setup a dev environment on Windows so that I can re-test the entire package to ensure each command works on windows.

**Comment by thexaib** [comment] 2024-04-19 20:06
I am getting same error on MacOS 14.3.1 , when plugins are registered by  `ModulesPlugin::make()` , it causes problem. My module from nWidart/laravel-modules is working fine if `ModulesPlugin::make()` is not called

Error:
```
 Class "Modules\Consents\app\Filament\ConsentsPlugin" not found

  at vendor/coolsam/modules/src/ModulesPlugin.php:22
     18▕         $panel
     19▕             ->topNavigation(config('filament-modules.clusters.enabled', false) && config('filament-modules.clusters.use-top-navigation', false));
     20▕         $plugins = $this->getModulePlugins();
     21▕         foreach ($plugins as $modulePlugin) {
  ➜  22▕             $panel->plugin($modulePlugin::make());
     23▕         }
     24▕     }
     25▕ 
     26▕     public function boot(Panel $panel): void

      +2 vendor frames 

  3   app/Providers/Filament/SupervisorPanelProvider.php:81
      Filament\Panel::plugins()
      +35 vendor frames 

  39  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Filament\FilamentServiceProvider))

```

**Comment by coolsam726** [comment] 2024-04-20 07:26
Please try v4.0.4 and confirm to me that it fixes the issue. Thanks.

**Comment by thexaib** [comment] 2024-04-20 07:40
Working Now. Thanks

**Comment by coolsam726** [comment] 2024-04-20 07:57
Thanks for the feedback @thexaib. If you experience any other issues, don't hesitate to post them.

**Comment by paulmercs** [comment] 2024-04-22 01:47
I am having this the same issue. When i use this command php artisan module:filament:install Hris
 Error 

  Class "Modules\Hris\Providers\HrisServiceProvider" not found

  at vendor\laravel\framework\src\Illuminate\Foundation\Application.php:851
    847▕      * @return \Illuminate\Support\ServiceProvider
    848▕      */
    849▕     public function resolveProvider($provider)
    850▕     {
  ➜ 851▕         return new $provider($this);
    852▕     }
    853▕
    854▕     /**
    855▕      * Mark the given provider as registered.

  1   vendor\laravel\framework\src\Illuminate\Foundation\Application.php:785
      Illuminate\Foundation\Application::resolveProvider("Modules\Hris\Providers\HrisServiceProvider")

  2   vendor\coolsam\modules\src\ModulesServiceProvider.php:74
      Illuminate\Foundation\Application::register("Modules\Hris\Providers\HrisServiceProvider")
      
      I am using the v4.0.4 laravel 10

**Comment by Mike-Hawwke** [comment] 2024-04-22 10:23
Hi @coolsam726 ,


I still have problems with your code

For reasons of simplicity I took a server directly and did the installation on it
But I still end up with the same kind of error

I don't understand where the problem comes from

![2024-04-22 122207](https://github.com/savannabits/filament-modules/assets/166394362/bd31945e-fcaa-4d6e-9827-202500a1e789)
![2024-04-22 122242](https://github.com/savannabits/filament-modules/assets/166394362/3fe5d48a-905c-451b-8913-3491bfa2e72d)


Thank you for your help

**Comment by Mike-Hawwke** [comment] 2024-04-22 14:32
I can't solve the problem, can you help me @coolsam726 ?


Here's where I'm stuck

I am now on server
When I do the installation no problem
I create my module
but when I want to install it I get this error that appears
![2024-04-22 163017](https://github.com/savannabits/filament-modules/assets/166394362/6c3a84e5-f05b-487a-8495-aeddb58d7280)

**Comment by coolsam726** [comment] 2024-04-24 15:54
Closing for now till I hear back from you.

**Closed** 2024-04-24 15:54 UTC
Labels: bug
