### ISSUE TITLE
Cannot create more than 1 filament context

### ISSUE THREAD

**Issue by LukasFreyCZ** [savannabits/filament-modules#11] opened 2023-02-05 21:38 UTC
Creating a second filament context cuases the following error to pop up:
```
   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [cache] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:891
    887▕ 
    888▕         try {
    889▕             $reflector = new ReflectionClass($concrete);
    890▕         } catch (ReflectionException $e) {
  ➜ 891▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    892▕         }
    893▕ 
    894▕         // If the type is not instantiable, the developer is attempting to resolve
    895▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Nwidart\Modules\FileRepository::__construct(Object(Illuminate\Foundation\Application))

      +8 vendor frames 
  10  [internal]:0
      Nwidart\Modules\FileRepository::__construct(Object(Illuminate\Foundation\Application))
```

EDIT: the first context doesn't work either, the whole app will fail because of this error. 

It is caused probably by this line in the generated filament config:
```php
        'path' => module_path($moduleName, "$contextPath/Pages"),
```

**Comment by LukasFreyCZ** [comment] 2023-02-06 20:06
This is NOT a solution, only a temporary workaround:
replacing the pre-generated module_path calls:
```
'path' => module_path($moduleName, "$contextPath/Pages"),
```
with base_path calls:
```
'path' => base_path("Modules/<ModuleName>/<FilamentContextName>/Pages"),
```

will fix it.

**Comment by husam-tariq** [comment] 2023-02-15 02:01
Same problem ??

**Comment by coolsam726** [comment] 2023-02-26 16:46
> 

This might be a bug, please include the Steps to Reproduce so that I can investigate it further.

**Comment by otavio-araujo** [comment] 2023-03-03 01:01
Yeah, I got the same "Target class [cache] does not exist" error here. But, i was abble to create the module, but when i refreshed the page, i got this errorÇ

Target class [cache] does not exist.

`  * @throws \Illuminate\Contracts\Container\BindingResolutionException

     * @throws \Illuminate\Contracts\Container\CircularDependencyException

     */

    public function build($concrete)

    {

        // If the concrete type is actually a Closure, we will just execute it and

        // hand back the results of the functions, which allows functions to be

        // used as resolvers for more fine-tuned resolution of these objects.

        if ($concrete instanceof Closure) {

            return $concrete($this, $this->getLastParameterOverride());

        }



        try {

            $reflector = new ReflectionClass($concrete);

        } catch (ReflectionException $e) {

            throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);

        }



        // If the type is not instantiable, the developer is attempting to resolve

        // an abstract type such as an Interface or Abstract Class and there is

        // no binding registered for the abstractions so we need to bail out.

        if (! $reflector->isInstantiable()) {

            return $this->notInstantiable($concrete);

        }



        $this->buildStack[] = $concrete;



        $constructor = $reflector->getConstructor();`

**Comment by coolsam726** [comment] 2023-03-03 05:09
> This is NOT a solution, only a temporary workaround: replacing the pre-generated module_path calls:
> 
> ```
> 'path' => module_path($moduleName, "$contextPath/Pages"),
> ```
> 
> with base_path calls:
> 
> ```
> 'path' => base_path("Modules/<ModuleName>/<FilamentContextName>/Pages"),
> ```
> 
> will fix it.

This gives me a pretty good starting point. Let me have a look at this.

**Comment by jgmuchiri** [comment] 2023-03-13 17:14
Couldn't get this to work on my end either.

For now, I'm using this https://gist.github.com/jgmuchiri/078ed20628613331fcda6ce655331a19 to register resources, pages and widgets.

> Could use some optimization but it's serving the purpose in the interim.

**Comment by coolsam726** [comment] 2023-07-17 10:32
On my end everything seems to be working ok. If this persists, kindly try the latest version which includes this PR #27 and if it doesn't fix it, install livewire/livewire again using `composer require livewire/livewire`. Closing for now.

**Closed by coolsam726** 2023-07-17 10:32 UTC
