### ISSUE TITLE
Custom guard not working

### ISSUE THREAD

**Issue by lukas-frey** [savannabits/filament-modules#13] opened 2023-02-06 20:29 UTC
When I use a custom guard and log into the dashboard, I get this error:
```php
Filament\FilamentManager::getUserAvatarUrl(): Argument #1 ($user) must be of type 
Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given
```

**Comment by coolsam726** [comment] 2023-02-26 16:48
@LukasFreyCZ kindly post the steps to reproduce or your guard setup to speed up diagnosis on my end. Thanks.

**Comment by coolsam726** [comment] 2024-04-14 13:36
Closing this as I couldn't re-produce. If the issue is still affecting you please feel free to reopen.

**Closed** 2024-04-14 13:37 UTC
